---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpbin-config
  namespace: httpbin-test
data:
  MODE: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          env:
            - name: MODE
              valueFrom:
                configMapKeyRef:
                  name: httpbin-config
                  key: MODE
          livenessProbe:
            httpGet:
              path: /status/200
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin-test
spec:
  type: NodePort
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32500